-- =====================================================================
-- MOVIE TICKET BOOKING SYSTEM - QUERIES
-- =====================================================================

-- 1. List all movies released in 2025, newest first.
SELECT title, release_date, certification
FROM movies
WHERE EXTRACT(YEAR FROM release_date) = 2025
ORDER BY release_date DESC;

-- 2. Find customers whose email domain is example.com.
SELECT full_name, email
FROM customers
WHERE email LIKE '%@example.com';

-- 3. Get all shows scheduled on 2026-07-16.
SELECT show_id, movie_id, screen_id, start_time
FROM shows
WHERE show_date = '2026-07-16';

-- 4. List all theatres located in Hyderabad.
SELECT theatre_name, address, phone
FROM theatres
WHERE city = 'Hyderabad';

-- 5. Count the number of movies per certification category.
SELECT certification, COUNT(*) AS movie_count
FROM movies
GROUP BY certification
ORDER BY movie_count DESC;

-- 6. Top 5 highest base-priced shows.
SELECT show_id, movie_id, base_price
FROM shows
ORDER BY base_price DESC
LIMIT 5;

-- 7. Compute the overall average review rating across all movies.
SELECT ROUND(AVG(rating), 2) AS overall_avg_rating
FROM reviews;

-- 8. Count seats available per seat type across the entire system.
SELECT seat_type, COUNT(*) AS total_seats
FROM seats
GROUP BY seat_type
ORDER BY total_seats DESC;

-- 9. List the 10 most recently registered customers.
SELECT full_name, email, created_at
FROM customers
ORDER BY created_at DESC
LIMIT 10;

-- 10. List all cancelled bookings.
SELECT booking_id, customer_id, show_id, total_amount
FROM bookings
WHERE booking_status = 'CANCELLED';

-- 11. INNER JOIN: list every movie with its associated genre names.
SELECT m.title, g.genre_name
FROM movies m
INNER JOIN movie_genres mg ON m.movie_id = mg.movie_id
INNER JOIN genres g ON mg.genre_id = g.genre_id
ORDER BY m.title;

-- 12. LEFT JOIN: find movies that have not received any review.
SELECT m.title
FROM movies m
LEFT JOIN reviews r ON m.movie_id = r.movie_id
WHERE r.review_id IS NULL;

-- 13. Multiple JOINs: full booking summary with customer, movie, screen and theatre.
SELECT b.booking_id, c.full_name, m.title, s.show_date, s.start_time,
       sc.screen_name, t.theatre_name, b.total_amount
FROM bookings b
JOIN customers c ON b.customer_id = c.customer_id
JOIN shows s ON b.show_id = s.show_id
JOIN movies m ON s.movie_id = m.movie_id
JOIN screens sc ON s.screen_id = sc.screen_id
JOIN theatres t ON sc.theatre_id = t.theatre_id
ORDER BY b.booking_id;

-- 14. HAVING: theatres that operate more than 1 screen.
SELECT t.theatre_name, COUNT(sc.screen_id) AS screen_count
FROM theatres t
JOIN screens sc ON t.theatre_id = sc.theatre_id
GROUP BY t.theatre_name
HAVING COUNT(sc.screen_id) > 1;

-- 15. Subquery: movies rated above the system-wide average rating.
SELECT m.title, ROUND(AVG(r.rating), 2) AS avg_rating
FROM movies m
JOIN reviews r ON m.movie_id = r.movie_id
GROUP BY m.title
HAVING AVG(r.rating) > (SELECT AVG(rating) FROM reviews);

-- 16. List the number of bookings made by each customer.
SELECT c.customer_id,
       c.full_name,
       COUNT(b.booking_id) AS total_bookings
FROM customers c
LEFT JOIN bookings b
ON c.customer_id = b.customer_id
GROUP BY c.customer_id, c.full_name
ORDER BY total_bookings DESC;

-- 17. Find the total revenue generated by each movie.
SELECT m.title,
       SUM(b.total_amount) AS total_revenue
FROM movies m
JOIN shows s
ON m.movie_id = s.movie_id
JOIN bookings b
ON s.show_id = b.show_id
WHERE b.booking_status = 'CONFIRMED'
GROUP BY m.title
ORDER BY total_revenue DESC;

-- 18. Display the number of shows scheduled for each movie.
SELECT m.title,
       COUNT(s.show_id) AS total_shows
FROM movies m
LEFT JOIN shows s
ON m.movie_id = s.movie_id
GROUP BY m.title
ORDER BY total_shows DESC;

-- 19. Find customers who have spent more than ₹1000 on confirmed bookings.
SELECT c.full_name,
       SUM(b.total_amount) AS total_spent
FROM customers c
JOIN bookings b
ON c.customer_id = b.customer_id
WHERE b.booking_status = 'CONFIRMED'
GROUP BY c.full_name
HAVING SUM(b.total_amount) > 1000
ORDER BY total_spent DESC;

-- 20. Find the highest-rated movie.
SELECT m.title,
       ROUND(AVG(r.rating), 2) AS average_rating
FROM movies m
JOIN reviews r
ON m.movie_id = r.movie_id
GROUP BY m.title
ORDER BY average_rating DESC
LIMIT 1;
